modLoader="javafml"
loaderVersion="${forge_loader_version_range}"
license="All rights reserved"
issueTrackerURL="https://github.com/TwelveIterationMods/Waystones/issues"

[[mods]]
modId="waystones"
version="${mod_version}"
displayName="Waystones"
displayURL="https://mods.twelveiterations.com/mc/waystones"
logoFile="waystones-icon.png"
credits="BlayTheNinth"
authors="BlayTheNinth"
description='''
Teleport back to activated waystones. For Survival, Adventure or Servers.
'''

[[dependencies.waystones]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.waystones]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.waystones]]
    modId="balm"
    mandatory=true
    versionRange="${balm_version_range}"
    ordering="NONE"
    side="BOTH"