modLoader="javafml"
loaderVersion="[41,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ModdingForBlockheads/Waystones/issues"

[[mods]]
modId="waystones"
version="${file.jarVersion}"
displayName="Waystones"
displayURL="https://blay09.net/mods/waystones"
logoFile="waystones-icon.png"
credits="BlayTheNinth"
authors="BlayTheNinth"
description='''
Teleport back to activated waystones. For Survival, Adventure or Servers.
'''

[[dependencies.waystones]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.waystones]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
[[dependencies.waystones]]
    modId="balm"
    mandatory=true
    versionRange="[4.0.0,)"
    ordering="NONE"
    side="BOTH"