modLoader="javafml"
loaderVersion="[24,)"
issueTrackerURL="https://github.com/blay09/Waystones/issues"
displayURL="https://minecraft.curseforge.com/projects/waystones"
authors="BlayTheNinth"
credits="Includes item icons by @JoeCreates released under CC-BY-SA 3.0"

[[mods]]
modId="waystones"
version="${file.jarVersion}"
displayName="Waystones"
description='''
Teleport back to activated waystones. For Survival, Adventure or Servers.
'''
